apiVersion: apps/v1
kind: Deployment
metadata:
  name: wunderpong-deployment
spec:
  selector:
    matchLabels:
      app: wunderpong-app
  template:
    metadata:
      labels:
        app: wunderpong-app
    spec:
      containers:
      - name: wunderpong
        image: 766261213300.dkr.ecr.eu-west-1.amazonaws.com/wunderpong:latest
        ports:
        - containerPort: 3000
        env:
          - name: NODE_ENV
            value: production
          - name: DATABASE_HOST
            value: wunderpong-postgres
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: wunderpong-database-config
                key: dbname
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: wunderpong-database-config
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: wunderpong-database-config
                key: password

---

apiVersion: v1
kind: Service
metadata:
  name: wunderpong-service
  labels:
    app: wunderpong-app
spec:
  ports:
   - port: 3000
  selector:
    app: wunderpong-app

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wunderpong-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: wunderpong.lab.wunder.dog
    http:
      paths:
      - backend:
          serviceName: wunderpong-service
          servicePort: 3000

---
